// <auto-generated />
using System;
using Infrastructure.Data.DbContextEntity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Exchange")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Branch");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Calle 44 # 12 - 70 Barrio Las Camelias",
                            CreateDate = new DateTime(2024, 3, 31, 16, 18, 42, 698, DateTimeKind.Local).AddTicks(8983),
                            Email = "gerencia@alpina.com",
                            Exchange = 2,
                            Name = "Alpina",
                            PhoneNumber = "3154096906",
                            Schedule = "8:00am - 6:00pm",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Address = "Calle 44 # 12 - 70 Barrio Las Camelias",
                            CreateDate = new DateTime(2024, 3, 29, 22, 44, 34, 258, DateTimeKind.Unspecified).AddTicks(3444),
                            Email = "gerencia@colanta.com",
                            Exchange = 2,
                            Name = "Colanta",
                            PhoneNumber = "3154096906",
                            Schedule = "8:00am - 6:00pm",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeUser")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Document = "1088027397",
                            LastName = "Franco Herrera",
                            Name = "Jorge Enrique",
                            Password = "12345678a",
                            PhoneNumber = "3148434889",
                            TypeUser = 1
                        },
                        new
                        {
                            Id = 2,
                            Document = "1094952038",
                            LastName = "Portela Guerra",
                            Name = "Juan Luis",
                            Password = "12345678a",
                            PhoneNumber = "3127248659",
                            TypeUser = 2
                        },
                        new
                        {
                            Id = 3,
                            Document = "1088352391",
                            LastName = "Perez Ortega",
                            Name = "Natalia",
                            Password = "12345678a",
                            PhoneNumber = "3022901238",
                            TypeUser = 2
                        });
                });

            modelBuilder.Entity("Domain.Branch", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithOne("Office")
                        .HasForeignKey("Domain.Branch", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Navigation("Office")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
